version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: it-landscape
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
